.github/workflows/code.yml: skip the test packages on archlinux temporarily
It has below issue when test-packages

	looking for conflicting packages...
	error: unresolvable package conflicts detected
	:: iptables-nft-1:1.8.10-2 and iptables-1:1.8.10-2 are in conflict. Remove iptables? [y/N]
	error: failed to prepare transaction (conflicting dependencies)
	:: iptables-nft-1:1.8.10-2 and iptables-1:1.8.10-2 are in conflict
	 -> error making: debhelper - exit status 4
	error installing repo packages
	Error: Process completed with exit code 1.

Signed-off-by: Philip Li <philip.li@intel.com>