programs/trinity/pkg/depends-dev: add backported dependency
the stock v6.12 linux-libc-dev package does not support latest
changes, resulting in compile errors like these:

In file included from /usr/include/stdio.h:34,
                 from include/utils.h:8,
                 from include/syscall.h:8,
                 from include/argtype-ops.h:5,
                 from struct_catalog.c:130:
struct_catalog.c:160:21: error: ‘struct io_uring_napi’ has no member named ‘opcode’
  160 |           .offset = offsetof(S, m), \
      |                     ^~~~~~~~

The backports repo has linux-libc-dev > 6.13 which is the minimum required to
support the new structures.

Signed-off-by: Frank Ranner <frank.ranner@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>