programs/aim7/pkg/PKGBUILD: fix build with gcc 14
GCC 14 turns -Wimplicit-function-declaration into an error by default,
breaking compilation of old C code that lacks string.h and other headers.

Supply -std=gnu89 to CFLAGS via S7setup so that it defaults to C89
standards where implicit declarations are allowed and only emit warnings.

Fixes build failure on test log:
disk_src.c:191:22: error: implicit declaration of function ‘strlen’ [...]

Signed-off-by: Philip Li <philip.li@intel.com>